package com.plantuml.skin;

@:enum
abstract ComponentType(String) /*implements Styleable*/ {
	final ARROW;
	//
	//	ACTOR_HEAD, ACTOR_TAIL,
	//
	//	BOUNDARY_HEAD, BOUNDARY_TAIL, CONTROL_HEAD, CONTROL_TAIL, ENTITY_HEAD, ENTITY_TAIL, QUEUE_HEAD, QUEUE_TAIL, DATABASE_HEAD, DATABASE_TAIL, COLLECTIONS_HEAD, COLLECTIONS_TAIL,
	//
	//	//
	//	ALIVE_BOX_CLOSE_CLOSE, ALIVE_BOX_CLOSE_OPEN, ALIVE_BOX_OPEN_CLOSE, ALIVE_BOX_OPEN_OPEN,
	//
	//	DELAY_TEXT, DESTROY,
	//
	//	DELAY_LINE, PARTICIPANT_LINE, CONTINUE_LINE,
	//
	//	//
	//	GROUPING_ELSE, GROUPING_HEADER, GROUPING_SPACE,
	//	//
	//	NEWPAGE, NOTE, NOTE_HEXAGONAL, NOTE_BOX, DIVIDER, REFERENCE, ENGLOBER,
	//
	//	//
	//	PARTICIPANT_HEAD, PARTICIPANT_TAIL
}
